language: java
sudo: required
services:
env:
  global:
    - ORACLE_COOKIE=sqldev
    - ORACLE_DOWNLOAD_DIR=stage
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE
    - SPRING_DATASOURCE_URL="jdbc:oracle:thin:@//localhost:1521/XE"
    - SPRING_DATASOURCE_USERNAME=system
    - SPRING_DATASOURCE_PASSWORD=travis

install:
  - .travis/oracle/download.sh
  - curl --cookie ./.travis/oracle/cookies.txt --cookie-jar ./.travis/oracle/cookies.txt --location --output src/demo/dep/ojdbc8.jar --user-agent "Mozilla/5.0" "http://download.oracle.com/otn/utilities_drivers/jdbc/122010/ojdbc8.jar"
  - md5sum src/demo/dep/ojdbc8.jar
  - .travis/oracle/install.sh

script:
  - cd src/demo
  - ./gradlew build
  - ./gradlew test
