language: java
sudo: required
services:
env:
  global:
    - ORACLE_COOKIE=sqldev
    - ORACLE_DOWNLOAD_DIR=stage
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE
    - SPRING_DATASOURCE_URL="jdbc:oracle:thin:@//localhost:1521/XE"
    - SPRING_DATASOURCE_USERNAME=travis
    - SPRING_DATASOURCE_PASSWORD=travis

install:
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh

script:
  - cd src/demo
  - ./gradlew build
  - ./gradlew test
